steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/tugas-akhir-praktcc/warehouse", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/tugas-akhir-praktcc/warehouse"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["run", "deploy", "warehouse", "--image", "gcr.io/tugas-akhir-praktcc/warehouse", "--region", "asia-east1"]
images:
  - gcr.io/tugas-akhir-praktcc/warehouse
